### ISSUE TITLE
browser closes when reconnecting to the internet

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/safe-mobile-browser#119]
STR:
1. Turn off internet connection
2. Open Browser
3. (Error message correctly displays saying no internet access available) > Press OK
4. Swipe up to display shortcuts to activate internet

Actual
5. Shortcut menu is deactivated and then the browser closes/crashes

Expected
5. Shortcut menu retains focus
6. Turn on internet
7. Close shortcut menu to return to browser
8. Browser remains open, and connects to SAFE

**Comment by ravinderjangra** [comment]
Fixed by #138

**Comment by S-Coyle** [comment]
Confirmed with @nadiaburborough that this is now resolved in the latest build
