### ISSUE TITLE
clicking safe:// links gives Error page not found

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe-mobile-browser#131]
Trying out safe://dweb which was working in SAFE Browser the home page loads ok, but clicking on any link gives a not found error. I'm using Android 7.1.

I am not logged into an account.

**Comment by ravinderjangra** [comment]
Thanks, @theWebalyst for reporting this. It's a known issue https://github.com/maidsafe/safe-mobile-browser/issues/87.
