### ISSUE TITLE
safe://safenetworkprimer2 website not loading properly

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe-mobile-browser#133]

**Comment by S-Coyle** [comment]
Verified as fixed on Android on PR #134 - safe://safenetworkprimer2 and safe://dweb "about" page now loading data

**Comment by S-Coyle** [comment]
Now also verified on iOS simulator. Note that the dweb about and blog pages show a spinner & do not load, but this does not appear to be the same issue as described in this bug report & suspicion is that it's an issue with the site itself. safe://safenetworkprimer2 loads data.
