### ISSUE TITLE
Add proper app themes to use light and dark mode

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe-mobile-browser#14]

**Comment by ravinderjangra** [comment]
fixed by #158.
Some PR(s) will be raised to refactor and apply theme on the app logs modal page.

**Comment by safesurfer** [comment]
In light theme, `No bookmarks!` text is not visible in `Bookmarks` page. either it is missing or the text colour is white.

**Comment by ravinderjangra** [comment]
@vigneshwara044 ^^^

**Comment by S-Coyle** [comment]
Verified on Android:
- `No Bookmarks` text is now showing.
- Tested while authenticated and while unauthenticated - all seems fine.
