### ISSUE TITLE
Add option to check, copy and delete log files from the settings page

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe-mobile-browser#167]

**Comment by safesurfer** [comment]
QA verified

**Comment by S-Coyle** [comment]
QA verified - Was able to `copy ` and `delete` the log files on both iOS and Android.
I assume the `check` part referred to in the title of this issue just means view the list of log files (if I assumed wrong then let me know @ravinderjangra )

**Comment by ravinderjangra** [comment]
The check options mean, to be able to see the list of the log files @S-Coyle
