### ISSUE TITLE
Numerical web addresses are converted into IP address

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe-mobile-browser#169]
Steps:
Try opening any SAFE url with numbers only. example safe://2020

Expected:
Website files should be fetched and rendered in the web view.

Actual result:
![](https://aws1.discourse-cdn.com/business5/uploads/safenetwork/original/3X/4/7/47a73d0bd6bf771af9f774e4e40d990f87c99e40.jpeg)

**Comment by ravinderjangra** [comment]
**URI parse behaviour:**
Whenever a numerical string is parsed and converted into a URI, the string is converted into an IP address. 

**Hack**
As we don't have control over the URI parser, we can append some string so that it doesn't get converted into an IP address and we can then remove the string before we fetch the content the and also update the address bar to show the address without appended string.

**Comment by ravinderjangra** [comment]
@S-Coyle, @safesurfer, @vigneshwara044 

What do you guys think about this issue?

**Comment by S-Coyle** [comment]
The suggested fix does sound a bit hacky, but if there's no viable alternative that could be implemented in the short term then I'd say it's better than just ignoring the issue.

**Comment by vigneshwara044** [comment]
yeah I second stephen, we'll implement hacky fix for v0.2

**Comment by ravinderjangra** [comment]
After looking into documentations I don't think that we'll be able to solve it without using some kind of hack. I will look into what other solutions we have and maybe then we can decide what to do.

**Comment by S-Coyle** [comment]
QA verified on Android
