### ISSUE TITLE
Error message "No internet connection" - should this say "No SAFE Network connection"?

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-mobile-browser#224]
Raised on the forum - https://safenetforum.org/t/new-release-safe-authenticator-v0-2-0-safe-mobile-browser-v0-3-0/31092/18?u=stephenc

**Comment by ravinderjangra** [comment]
Cross checked all the references for this error and we are using this only when the internet isn't available /disabled. It may be an issue during user testing.

**Comment by S-Coyle** [comment]
Closing issue, I also checked at the time of logging this and could find no reference to this error message for when the SAFE Network was not available. Have to assume that there was an internet connection drop at the time on the user's device
