### ISSUE TITLE
iOS - `safe://` prefix on URL can sometimes look squashed and be overlapped on page loading

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-mobile-browser#231]
See example:
![image](https://user-images.githubusercontent.com/37112040/74525612-5f4ed500-4f19-11ea-9fe9-006e75bd8478.png)

Reported on the forum. I've not been able to reproduce on Android. It seems to happen when pages are loading, so if a page is bigger/slower to load then this can be quite noticeable

**Comment by ravinderjangra** [comment]
This issue is iOS-specific and mostly related to the animation. I tried multiple methods to smooth this but wasn't able to resolve this. I will try to see if this can be improved otherwise I'll think so some other animation here.
