### ISSUE TITLE
Browser session not terminated when user logs out of authenticator

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe-mobile-browser#238]
If a user was to log out of the authenticator & login as a different user the initial browser session would still be active until the browser is manually re-authenticated.

Should we kill session if a user is no longer authenticated?

**Comment by ravinderjangra** [comment]
I am not sure if we want this cause the browser is using unregistered clients so technically the browser isn't authenticated with any user.

**Comment by S-Coyle** [comment]
@ravinderjangra Agreed, there is no need to associate to any specific user.

Not sure whether to close this issue - is there merit in exploring whether we should kill the browser authentication if, for example, a user logs out of the authenticator? 
Updating title & description to reflect this qn

**Comment by ravinderjangra** [comment]
Since the browser is using an unregistered session, it doesn't affect whether a user is logged on or not. The apps are independent (except authentication) and OS doesn't allow accessing the state b/w two app/processes, I'm not sure we can implement this.

**Comment by S-Coyle** [comment]
OK, let's close this then 👍
