### ISSUE TITLE
Possible for users to know whether browser was authenticated via icon or similar?

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-mobile-browser#239]
Suggestion from the forum [here](https://safenetforum.org/t/new-release-safe-authenticator-v0-2-0-safe-mobile-browser-v0-3-0/31092/36?u=stephenc)

The suggestion is that a user should be able to know at a glance whether the browser is authenticated or not, e.g. there could be an icon displayed on the browser.

**Comment by ravinderjangra** [comment]
This is a good small feature, I'll think of some way to add a status icon in the browser app.
