### ISSUE TITLE
0.5.0 [Settings].Help.FAQs link broken

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe-mobile-browser#255]
[Settings].Help.FAQs link is broken

Search on the forum throws up and old similar link https://safenetforum.org/t/faqs-safe-browser-mobile/29365

Search on the code here suggests 
 SafeMobileBrowser/SafeMobileBrowser/Helpers/Constants.cs
        public const string FaqUrl = "https://safenetforum.org/t/safe-mobile-browser-faqs

Would be nice if it did link somewhere up to date.

**Comment by frabrunelle** [comment]
Yes, it should link to https://safenetforum.org/t/faqs-safe-browser-mobile/29365

There is also a similar FAQ topic for the Authenticator: https://safenetforum.org/t/faqs-safe-authenticator-mobile/26683

I updated both of them about a month ago. I'll start working on a draft now to update them again 🙂

**Comment by ravinderjangra** [comment]
Thanks for reporting this @davidpbrown. I'm not sure how but it seems the forum link got updated to a different address. I'll update the app to use this new address and in parallel, we will update the content as well.
